# Generated by Django 5.1.3 on 2024-11-29 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('campus_id', models.AutoField(primary_key=True, serialize=False)),
                ('campus_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'campus',
            },
        ),
        migrations.CreateModel(
            name='InstructorCourse',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_id', models.IntegerField(default=0)),
                ('course_code', models.TextField(blank=True, null=True)),
                ('course_name', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('credit_hours', models.IntegerField(blank=True, null=True)),
                ('prerequisites', models.JSONField(blank=True, null=True)),
                ('school_year', models.TextField(blank=True, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instructor_course',
            },
        ),
        migrations.CreateModel(
            name='InstructorData',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_id', models.IntegerField(default=0)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('first_name', models.CharField(default='', max_length=255)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('employment_type', models.CharField(choices=[('regular', 'Regular'), ('cos', 'COS')], default='regular', max_length=10)),
                ('qualified_course', models.JSONField(default=dict)),
                ('availability_days', models.JSONField(default=list)),
                ('availability_times', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'instructors_data',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_id', models.IntegerField()),
                ('program_code', models.TextField(blank=True, null=True)),
                ('program_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Program',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=255)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='scheduling_system.campus')),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=255)),
                ('room_type', models.CharField(max_length=255)),
                ('availability_days', models.JSONField()),
                ('availability_times', models.JSONField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='scheduling_system.building')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='scheduling_system.campus')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='RoomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling_system.room')),
            ],
            options={
                'db_table': 'room_schedule',
            },
        ),
    ]
