# Generated by Django 5.1.1 on 2024-11-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling_system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instructor_name", models.CharField(max_length=200)),
                ("course_code", models.CharField(max_length=50)),
                ("course_name", models.CharField(max_length=200)),
                ("credit_hours", models.IntegerField()),
                ("semester", models.CharField(max_length=50)),
                ("program_name", models.CharField(max_length=100)),
                ("program_code", models.CharField(max_length=50)),
                ("room_number", models.CharField(max_length=100)),
                ("room_type", models.CharField(max_length=50)),
                ("building_name", models.CharField(max_length=100)),
                ("campus_name", models.CharField(max_length=100)),
                ("day", models.CharField(max_length=20)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("year_level", models.CharField(max_length=50)),
                ("section", models.CharField(max_length=100)),
                ("shift", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
